export default defineAppConfig({
  pages: [
    "pages/index/index",
    "pages/player/profile/index",
    "pages/player/income/index",
    "pages/player/disputes/index",
    "pages/player/availability/index",
    "pages/player/order-hall/index",
    "pages/player/game-signup/index",
    "pages/customer/home/index",
    "pages/customer/orders/index",
    "pages/customer/candidates/index",
    "pages/customer/game-order/index",
    "pages/customer/game-select/index",
    "pages/customer/order-detail/index",
    "pages/customer/wallet/index",
    "pages/customer/profile/index",
    "pages/customer/disputes/index",
    "pages/customer/dispute-create/index",
    "pages/customer/service-off/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "PW",
    navigationBarTextStyle: "black",
  },
});
