import type { ComponentType } from "react";
import {
  AlertTriangle,
  BadgeDollarSign,
  Banknote,
  Bell,
  BookOpen,
  Boxes,
  BriefcaseBusiness,
  ChartNoAxesCombined,
  ClipboardList,
  Gauge,
  Home,
  Megaphone,
  Radio,
  ReceiptText,
  ScrollText,
  Settings,
  SlidersHorizontal,
  Shield,
  ShieldAlert,
  Sparkles,
  Timer,
  User,
  Users,
  UsersRound,
  Wallet,
} from "lucide-react";
import type { MerchantModuleId, MerchantNavDomainId } from "./modules";

export type ModuleIcon = ComponentType<{ className?: string; size?: number }>;

export const MODULE_ICONS: Record<MerchantModuleId, ModuleIcon> = {
  work: Home,
  ai: Sparkles,
  dispatch: ClipboardList,
  sessions: Timer,
  customers: Users,
  players: User,
  "player-applications": ClipboardList,
  breaches: ShieldAlert,
  catalog: BookOpen,
  pricing: BadgeDollarSign,
  finance: Wallet,
  settlements: Banknote,
  disputes: ShieldAlert,
  audit: ScrollText,
  overview: Gauge,
  live: Radio,
  risk: AlertTriangle,
  finrisk: Shield,
  health: Bell,
  settings: Settings,
};

export const DOMAIN_ICONS: Record<MerchantNavDomainId, ModuleIcon> = {
  business: BriefcaseBusiness,
  orders: ReceiptText,
  people: UsersRound,
  catalog: Boxes,
  marketing: Megaphone,
  finance: Banknote,
  insights: ChartNoAxesCombined,
  settings: SlidersHorizontal,
};
