// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type HealthGetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthGetHealthResponses = {
    200: unknown;
};

export type ReadyReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ready';
};

export type ReadyReadyResponses = {
    200: unknown;
};

export type TenancyListTenantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/platform/tenants';
};

export type TenancyListTenantsResponses = {
    200: unknown;
};

export type TenancyCreateTenantData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/platform/tenants';
};

export type TenancyCreateTenantResponses = {
    201: unknown;
};

export type TenancyDeactivateTenantData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/platform/tenants/{id}/deactivate';
};

export type TenancyDeactivateTenantResponses = {
    200: unknown;
};

export type TenancyResolveTenantData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/public/tenant-resolve';
};

export type TenancyResolveTenantResponses = {
    200: unknown;
};

export type AuditListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/audit';
};

export type AuditListResponses = {
    200: unknown;
};

export type PlatformAuditPlatformListData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/api/v1/platform/tenants/{tenantId}/audit';
};

export type PlatformAuditPlatformListResponses = {
    200: unknown;
};

export type AuthLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type AuthLoginResponses = {
    201: unknown;
};

export type AuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type AuthRefreshResponses = {
    201: unknown;
};

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type AuthLogoutResponses = {
    201: unknown;
};

export type AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type AuthMeResponses = {
    200: unknown;
};

export type MePlatformMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/platform/me';
};

export type MePlatformMeResponses = {
    200: unknown;
};

export type MeTenantMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/me';
};

export type MeTenantMeResponses = {
    200: unknown;
};

export type EntitlementsListTenantFeaturesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/features';
};

export type EntitlementsListTenantFeaturesResponses = {
    200: unknown;
};

export type EntitlementsAddonCapabilityData = {
    body?: never;
    path: {
        featureKey: string;
    };
    query?: never;
    url: '/api/v1/tenant/addon/{featureKey}';
};

export type EntitlementsAddonCapabilityResponses = {
    200: unknown;
};

export type EntitlementsListEntitlementsData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/api/v1/platform/tenants/{tenantId}/entitlements';
};

export type EntitlementsListEntitlementsResponses = {
    200: unknown;
};

export type EntitlementsSetEntitlementData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/api/v1/platform/tenants/{tenantId}/entitlements';
};

export type EntitlementsSetEntitlementResponses = {
    201: unknown;
};

export type TenantConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/config';
};

export type TenantConfigGetResponses = {
    200: unknown;
};

export type TenantConfigSaveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/config';
};

export type TenantConfigSaveResponses = {
    201: unknown;
};

export type TenantConfigRollbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/config/rollback';
};

export type TenantConfigRollbackResponses = {
    201: unknown;
};

export type TenantConfigVersionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/config/versions';
};

export type TenantConfigVersionsResponses = {
    200: unknown;
};

export type StorefrontConfigGetConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/public/storefront/config';
};

export type StorefrontConfigGetConfigResponses = {
    200: unknown;
};

export type CustomersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/customers';
};

export type CustomersListResponses = {
    200: unknown;
};

export type CustomersCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/customers';
};

export type CustomersCreateResponses = {
    201: unknown;
};

export type CustomersRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/customers/{id}';
};

export type CustomersRemoveResponses = {
    200: unknown;
};

export type CustomersGetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/customers/{id}';
};

export type CustomersGetResponses = {
    200: unknown;
};

export type CustomersUpdateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/customers/{id}';
};

export type CustomersUpdateResponses = {
    200: unknown;
};

export type CustomersBindData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/customers/{id}/account';
};

export type CustomersBindResponses = {
    201: unknown;
};

export type CustomerSelfMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/customer/me';
};

export type CustomerSelfMeResponses = {
    200: unknown;
};

export type CustomerSelfMyOrdersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/customer/orders';
};

export type CustomerSelfMyOrdersResponses = {
    200: {
        data: Array<{
            /**
             * 订单 id
             */
            id: string;
            /**
             * 租户 id
             */
            tenantId: string;
            /**
             * 订单号
             */
            orderNo: string;
            /**
             * 客户档案 id
             */
            customerProfileId: string;
            /**
             * 客户名
             */
            customerName: string;
            /**
             * 订单状态
             */
            status: string;
            /**
             * 计划开始
             */
            scheduledStartAt: string | null;
            /**
             * 备注
             */
            remark: string | null;
            /**
             * 乐观锁版本
             */
            version: number;
            /**
             * 创建时间
             */
            createdAt: string;
            /**
             * 更新时间
             */
            updatedAt: string;
            requirement: {
                /**
                 * 需求描述
                 */
                description: string;
                /**
                 * 游戏 id
                 */
                gameId?: string | null;
                /**
                 * 服务产品 id
                 */
                serviceProductId?: string | null;
                /**
                 * 游戏名
                 */
                gameName?: string | null;
                /**
                 * 产品名
                 */
                productName?: string | null;
                /**
                 * 期望开始时间
                 */
                desiredStartAt?: string | null;
                /**
                 * 时长（秒）
                 */
                durationSeconds?: number;
                /**
                 * 最低预算（十进制字符串分，>=0）
                 */
                minBudgetFen?: string;
                /**
                 * 最高预算（十进制字符串分，>=0）
                 */
                maxBudgetFen?: string;
                /**
                 * 备注
                 */
                note?: string | null;
            } | null;
            snapshot: Array<{
                /**
                 * 服务产品 id
                 */
                serviceProductId: string | null;
                /**
                 * 产品名
                 */
                productName: string;
                /**
                 * 区服名
                 */
                regionName: string | null;
                /**
                 * 时长（秒）
                 */
                durationSeconds: number;
                /**
                 * 单价（十进制字符串分，>0）
                 */
                unitPriceFen: string;
                /**
                 * 陪玩成本（十进制字符串分，>=0）
                 */
                playerCostFen: string;
                /**
                 * 行小计（十进制字符串分，>0）
                 */
                lineTotalFen: string;
                /**
                 * 币种
                 */
                currency: string;
            }> | null;
            timeline: Array<{
                /**
                 * 事件 id
                 */
                id: string;
                /**
                 * 事件类型
                 */
                eventType: string;
                /**
                 * 原状态
                 */
                fromStatus: string | null;
                /**
                 * 目标状态
                 */
                toStatus: string | null;
                /**
                 * 发生时间
                 */
                occurredAt: string;
            }>;
        }>;
    };
};

export type CustomerSelfMyOrdersResponse = CustomerSelfMyOrdersResponses[keyof CustomerSelfMyOrdersResponses];

export type CustomerSelfCreateOrderData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/customer/orders';
};

export type CustomerSelfCreateOrderResponses = {
    201: {
        /**
         * 订单视图（金额字段为十进制字符串分）
         */
        data: {
            /**
             * 订单 id
             */
            id: string;
            /**
             * 租户 id
             */
            tenantId: string;
            /**
             * 订单号
             */
            orderNo: string;
            /**
             * 客户档案 id
             */
            customerProfileId: string;
            /**
             * 客户名
             */
            customerName: string;
            /**
             * 订单状态
             */
            status: string;
            /**
             * 计划开始
             */
            scheduledStartAt: string | null;
            /**
             * 备注
             */
            remark: string | null;
            /**
             * 乐观锁版本
             */
            version: number;
            /**
             * 创建时间
             */
            createdAt: string;
            /**
             * 更新时间
             */
            updatedAt: string;
            requirement: {
                /**
                 * 需求描述
                 */
                description: string;
                /**
                 * 游戏 id
                 */
                gameId?: string | null;
                /**
                 * 服务产品 id
                 */
                serviceProductId?: string | null;
                /**
                 * 游戏名
                 */
                gameName?: string | null;
                /**
                 * 产品名
                 */
                productName?: string | null;
                /**
                 * 期望开始时间
                 */
                desiredStartAt?: string | null;
                /**
                 * 时长（秒）
                 */
                durationSeconds?: number;
                /**
                 * 最低预算（十进制字符串分，>=0）
                 */
                minBudgetFen?: string;
                /**
                 * 最高预算（十进制字符串分，>=0）
                 */
                maxBudgetFen?: string;
                /**
                 * 备注
                 */
                note?: string | null;
            } | null;
            snapshot: Array<{
                /**
                 * 服务产品 id
                 */
                serviceProductId: string | null;
                /**
                 * 产品名
                 */
                productName: string;
                /**
                 * 区服名
                 */
                regionName: string | null;
                /**
                 * 时长（秒）
                 */
                durationSeconds: number;
                /**
                 * 单价（十进制字符串分，>0）
                 */
                unitPriceFen: string;
                /**
                 * 陪玩成本（十进制字符串分，>=0）
                 */
                playerCostFen: string;
                /**
                 * 行小计（十进制字符串分，>0）
                 */
                lineTotalFen: string;
                /**
                 * 币种
                 */
                currency: string;
            }> | null;
            timeline: Array<{
                /**
                 * 事件 id
                 */
                id: string;
                /**
                 * 事件类型
                 */
                eventType: string;
                /**
                 * 原状态
                 */
                fromStatus: string | null;
                /**
                 * 目标状态
                 */
                toStatus: string | null;
                /**
                 * 发生时间
                 */
                occurredAt: string;
            }>;
        };
    };
};

export type CustomerSelfCreateOrderResponse = CustomerSelfCreateOrderResponses[keyof CustomerSelfCreateOrderResponses];

export type CustomerSelfConfirmCompleteData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/tenant/customer/orders/{orderId}/complete';
};

export type CustomerSelfConfirmCompleteResponses = {
    201: {
        /**
         * 订单核算结果
         */
        data: {
            /**
             * earning id
             */
            earningId: string;
            /**
             * 陪玩分成（十进制字符串分，>=0）
             */
            playerShareFen: string;
        };
    };
};

export type CustomerSelfConfirmCompleteResponse = CustomerSelfConfirmCompleteResponses[keyof CustomerSelfConfirmCompleteResponses];

export type OrdersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/orders';
};

export type OrdersListResponses = {
    200: {
        data: Array<{
            /**
             * 订单 id
             */
            id: string;
            /**
             * 租户 id
             */
            tenantId: string;
            /**
             * 订单号
             */
            orderNo: string;
            /**
             * 客户档案 id
             */
            customerProfileId: string;
            /**
             * 客户名
             */
            customerName: string;
            /**
             * 订单状态
             */
            status: string;
            /**
             * 计划开始
             */
            scheduledStartAt: string | null;
            /**
             * 备注
             */
            remark: string | null;
            /**
             * 乐观锁版本
             */
            version: number;
            /**
             * 创建时间
             */
            createdAt: string;
            /**
             * 更新时间
             */
            updatedAt: string;
            requirement: {
                /**
                 * 需求描述
                 */
                description: string;
                /**
                 * 游戏 id
                 */
                gameId?: string | null;
                /**
                 * 服务产品 id
                 */
                serviceProductId?: string | null;
                /**
                 * 游戏名
                 */
                gameName?: string | null;
                /**
                 * 产品名
                 */
                productName?: string | null;
                /**
                 * 期望开始时间
                 */
                desiredStartAt?: string | null;
                /**
                 * 时长（秒）
                 */
                durationSeconds?: number;
                /**
                 * 最低预算（十进制字符串分，>=0）
                 */
                minBudgetFen?: string;
                /**
                 * 最高预算（十进制字符串分，>=0）
                 */
                maxBudgetFen?: string;
                /**
                 * 备注
                 */
                note?: string | null;
            } | null;
            snapshot: Array<{
                /**
                 * 服务产品 id
                 */
                serviceProductId: string | null;
                /**
                 * 产品名
                 */
                productName: string;
                /**
                 * 区服名
                 */
                regionName: string | null;
                /**
                 * 时长（秒）
                 */
                durationSeconds: number;
                /**
                 * 单价（十进制字符串分，>0）
                 */
                unitPriceFen: string;
                /**
                 * 陪玩成本（十进制字符串分，>=0）
                 */
                playerCostFen: string;
                /**
                 * 行小计（十进制字符串分，>0）
                 */
                lineTotalFen: string;
                /**
                 * 币种
                 */
                currency: string;
            }> | null;
            timeline: Array<{
                /**
                 * 事件 id
                 */
                id: string;
                /**
                 * 事件类型
                 */
                eventType: string;
                /**
                 * 原状态
                 */
                fromStatus: string | null;
                /**
                 * 目标状态
                 */
                toStatus: string | null;
                /**
                 * 发生时间
                 */
                occurredAt: string;
            }>;
        }>;
    };
};

export type OrdersListResponse = OrdersListResponses[keyof OrdersListResponses];

export type OrdersCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/orders';
};

export type OrdersCreateResponses = {
    201: {
        /**
         * 订单视图（金额字段为十进制字符串分）
         */
        data: {
            /**
             * 订单 id
             */
            id: string;
            /**
             * 租户 id
             */
            tenantId: string;
            /**
             * 订单号
             */
            orderNo: string;
            /**
             * 客户档案 id
             */
            customerProfileId: string;
            /**
             * 客户名
             */
            customerName: string;
            /**
             * 订单状态
             */
            status: string;
            /**
             * 计划开始
             */
            scheduledStartAt: string | null;
            /**
             * 备注
             */
            remark: string | null;
            /**
             * 乐观锁版本
             */
            version: number;
            /**
             * 创建时间
             */
            createdAt: string;
            /**
             * 更新时间
             */
            updatedAt: string;
            requirement: {
                /**
                 * 需求描述
                 */
                description: string;
                /**
                 * 游戏 id
                 */
                gameId?: string | null;
                /**
                 * 服务产品 id
                 */
                serviceProductId?: string | null;
                /**
                 * 游戏名
                 */
                gameName?: string | null;
                /**
                 * 产品名
                 */
                productName?: string | null;
                /**
                 * 期望开始时间
                 */
                desiredStartAt?: string | null;
                /**
                 * 时长（秒）
                 */
                durationSeconds?: number;
                /**
                 * 最低预算（十进制字符串分，>=0）
                 */
                minBudgetFen?: string;
                /**
                 * 最高预算（十进制字符串分，>=0）
                 */
                maxBudgetFen?: string;
                /**
                 * 备注
                 */
                note?: string | null;
            } | null;
            snapshot: Array<{
                /**
                 * 服务产品 id
                 */
                serviceProductId: string | null;
                /**
                 * 产品名
                 */
                productName: string;
                /**
                 * 区服名
                 */
                regionName: string | null;
                /**
                 * 时长（秒）
                 */
                durationSeconds: number;
                /**
                 * 单价（十进制字符串分，>0）
                 */
                unitPriceFen: string;
                /**
                 * 陪玩成本（十进制字符串分，>=0）
                 */
                playerCostFen: string;
                /**
                 * 行小计（十进制字符串分，>0）
                 */
                lineTotalFen: string;
                /**
                 * 币种
                 */
                currency: string;
            }> | null;
            timeline: Array<{
                /**
                 * 事件 id
                 */
                id: string;
                /**
                 * 事件类型
                 */
                eventType: string;
                /**
                 * 原状态
                 */
                fromStatus: string | null;
                /**
                 * 目标状态
                 */
                toStatus: string | null;
                /**
                 * 发生时间
                 */
                occurredAt: string;
            }>;
        };
    };
};

export type OrdersCreateResponse = OrdersCreateResponses[keyof OrdersCreateResponses];

export type OrdersGetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/orders/{id}';
};

export type OrdersGetResponses = {
    200: {
        /**
         * 订单视图（金额字段为十进制字符串分）
         */
        data: {
            /**
             * 订单 id
             */
            id: string;
            /**
             * 租户 id
             */
            tenantId: string;
            /**
             * 订单号
             */
            orderNo: string;
            /**
             * 客户档案 id
             */
            customerProfileId: string;
            /**
             * 客户名
             */
            customerName: string;
            /**
             * 订单状态
             */
            status: string;
            /**
             * 计划开始
             */
            scheduledStartAt: string | null;
            /**
             * 备注
             */
            remark: string | null;
            /**
             * 乐观锁版本
             */
            version: number;
            /**
             * 创建时间
             */
            createdAt: string;
            /**
             * 更新时间
             */
            updatedAt: string;
            requirement: {
                /**
                 * 需求描述
                 */
                description: string;
                /**
                 * 游戏 id
                 */
                gameId?: string | null;
                /**
                 * 服务产品 id
                 */
                serviceProductId?: string | null;
                /**
                 * 游戏名
                 */
                gameName?: string | null;
                /**
                 * 产品名
                 */
                productName?: string | null;
                /**
                 * 期望开始时间
                 */
                desiredStartAt?: string | null;
                /**
                 * 时长（秒）
                 */
                durationSeconds?: number;
                /**
                 * 最低预算（十进制字符串分，>=0）
                 */
                minBudgetFen?: string;
                /**
                 * 最高预算（十进制字符串分，>=0）
                 */
                maxBudgetFen?: string;
                /**
                 * 备注
                 */
                note?: string | null;
            } | null;
            snapshot: Array<{
                /**
                 * 服务产品 id
                 */
                serviceProductId: string | null;
                /**
                 * 产品名
                 */
                productName: string;
                /**
                 * 区服名
                 */
                regionName: string | null;
                /**
                 * 时长（秒）
                 */
                durationSeconds: number;
                /**
                 * 单价（十进制字符串分，>0）
                 */
                unitPriceFen: string;
                /**
                 * 陪玩成本（十进制字符串分，>=0）
                 */
                playerCostFen: string;
                /**
                 * 行小计（十进制字符串分，>0）
                 */
                lineTotalFen: string;
                /**
                 * 币种
                 */
                currency: string;
            }> | null;
            timeline: Array<{
                /**
                 * 事件 id
                 */
                id: string;
                /**
                 * 事件类型
                 */
                eventType: string;
                /**
                 * 原状态
                 */
                fromStatus: string | null;
                /**
                 * 目标状态
                 */
                toStatus: string | null;
                /**
                 * 发生时间
                 */
                occurredAt: string;
            }>;
        };
    };
};

export type OrdersGetResponse = OrdersGetResponses[keyof OrdersGetResponses];

export type OrdersConfirmData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/orders/{id}/confirm';
};

export type OrdersConfirmResponses = {
    201: {
        /**
         * 订单视图（金额字段为十进制字符串分）
         */
        data: {
            /**
             * 订单 id
             */
            id: string;
            /**
             * 租户 id
             */
            tenantId: string;
            /**
             * 订单号
             */
            orderNo: string;
            /**
             * 客户档案 id
             */
            customerProfileId: string;
            /**
             * 客户名
             */
            customerName: string;
            /**
             * 订单状态
             */
            status: string;
            /**
             * 计划开始
             */
            scheduledStartAt: string | null;
            /**
             * 备注
             */
            remark: string | null;
            /**
             * 乐观锁版本
             */
            version: number;
            /**
             * 创建时间
             */
            createdAt: string;
            /**
             * 更新时间
             */
            updatedAt: string;
            requirement: {
                /**
                 * 需求描述
                 */
                description: string;
                /**
                 * 游戏 id
                 */
                gameId?: string | null;
                /**
                 * 服务产品 id
                 */
                serviceProductId?: string | null;
                /**
                 * 游戏名
                 */
                gameName?: string | null;
                /**
                 * 产品名
                 */
                productName?: string | null;
                /**
                 * 期望开始时间
                 */
                desiredStartAt?: string | null;
                /**
                 * 时长（秒）
                 */
                durationSeconds?: number;
                /**
                 * 最低预算（十进制字符串分，>=0）
                 */
                minBudgetFen?: string;
                /**
                 * 最高预算（十进制字符串分，>=0）
                 */
                maxBudgetFen?: string;
                /**
                 * 备注
                 */
                note?: string | null;
            } | null;
            snapshot: Array<{
                /**
                 * 服务产品 id
                 */
                serviceProductId: string | null;
                /**
                 * 产品名
                 */
                productName: string;
                /**
                 * 区服名
                 */
                regionName: string | null;
                /**
                 * 时长（秒）
                 */
                durationSeconds: number;
                /**
                 * 单价（十进制字符串分，>0）
                 */
                unitPriceFen: string;
                /**
                 * 陪玩成本（十进制字符串分，>=0）
                 */
                playerCostFen: string;
                /**
                 * 行小计（十进制字符串分，>0）
                 */
                lineTotalFen: string;
                /**
                 * 币种
                 */
                currency: string;
            }> | null;
            timeline: Array<{
                /**
                 * 事件 id
                 */
                id: string;
                /**
                 * 事件类型
                 */
                eventType: string;
                /**
                 * 原状态
                 */
                fromStatus: string | null;
                /**
                 * 目标状态
                 */
                toStatus: string | null;
                /**
                 * 发生时间
                 */
                occurredAt: string;
            }>;
        };
    };
};

export type OrdersConfirmResponse = OrdersConfirmResponses[keyof OrdersConfirmResponses];

export type OrdersCancelData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/orders/{id}/cancel';
};

export type OrdersCancelResponses = {
    201: {
        /**
         * 订单视图（金额字段为十进制字符串分）
         */
        data: {
            /**
             * 订单 id
             */
            id: string;
            /**
             * 租户 id
             */
            tenantId: string;
            /**
             * 订单号
             */
            orderNo: string;
            /**
             * 客户档案 id
             */
            customerProfileId: string;
            /**
             * 客户名
             */
            customerName: string;
            /**
             * 订单状态
             */
            status: string;
            /**
             * 计划开始
             */
            scheduledStartAt: string | null;
            /**
             * 备注
             */
            remark: string | null;
            /**
             * 乐观锁版本
             */
            version: number;
            /**
             * 创建时间
             */
            createdAt: string;
            /**
             * 更新时间
             */
            updatedAt: string;
            requirement: {
                /**
                 * 需求描述
                 */
                description: string;
                /**
                 * 游戏 id
                 */
                gameId?: string | null;
                /**
                 * 服务产品 id
                 */
                serviceProductId?: string | null;
                /**
                 * 游戏名
                 */
                gameName?: string | null;
                /**
                 * 产品名
                 */
                productName?: string | null;
                /**
                 * 期望开始时间
                 */
                desiredStartAt?: string | null;
                /**
                 * 时长（秒）
                 */
                durationSeconds?: number;
                /**
                 * 最低预算（十进制字符串分，>=0）
                 */
                minBudgetFen?: string;
                /**
                 * 最高预算（十进制字符串分，>=0）
                 */
                maxBudgetFen?: string;
                /**
                 * 备注
                 */
                note?: string | null;
            } | null;
            snapshot: Array<{
                /**
                 * 服务产品 id
                 */
                serviceProductId: string | null;
                /**
                 * 产品名
                 */
                productName: string;
                /**
                 * 区服名
                 */
                regionName: string | null;
                /**
                 * 时长（秒）
                 */
                durationSeconds: number;
                /**
                 * 单价（十进制字符串分，>0）
                 */
                unitPriceFen: string;
                /**
                 * 陪玩成本（十进制字符串分，>=0）
                 */
                playerCostFen: string;
                /**
                 * 行小计（十进制字符串分，>0）
                 */
                lineTotalFen: string;
                /**
                 * 币种
                 */
                currency: string;
            }> | null;
            timeline: Array<{
                /**
                 * 事件 id
                 */
                id: string;
                /**
                 * 事件类型
                 */
                eventType: string;
                /**
                 * 原状态
                 */
                fromStatus: string | null;
                /**
                 * 目标状态
                 */
                toStatus: string | null;
                /**
                 * 发生时间
                 */
                occurredAt: string;
            }>;
        };
    };
};

export type OrdersCancelResponse = OrdersCancelResponses[keyof OrdersCancelResponses];

export type OrdersStaffConfirmData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/orders/{id}/staff-confirm';
};

export type OrdersStaffConfirmResponses = {
    201: {
        /**
         * 订单核算结果
         */
        data: {
            /**
             * earning id
             */
            earningId: string;
            /**
             * 陪玩分成（十进制字符串分，>=0）
             */
            playerShareFen: string;
        };
    };
};

export type OrdersStaffConfirmResponse = OrdersStaffConfirmResponses[keyof OrdersStaffConfirmResponses];

export type PlatformFinanceGetData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/api/v1/platform/tenants/{tenantId}/finance-rules';
};

export type PlatformFinanceGetResponses = {
    200: unknown;
};

export type PlatformFinanceSetData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/api/v1/platform/tenants/{tenantId}/finance-rules';
};

export type PlatformFinanceSetResponses = {
    200: unknown;
};

export type TenantFinanceGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/finance-rules';
};

export type TenantFinanceGetResponses = {
    200: {
        data: {
            /**
             * 平台费率 bp
             */
            platformFeeBp: number;
            /**
             * 门店抽成 bp
             */
            storeCutBp: number;
        };
    };
};

export type TenantFinanceGetResponse = TenantFinanceGetResponses[keyof TenantFinanceGetResponses];

export type TenantFinanceSetStoreCutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/finance-rules/store-cut';
};

export type TenantFinanceSetStoreCutResponses = {
    201: unknown;
};

export type TenantFinancePreviewData = {
    /**
     * 分账试算入参（十进制字符串分）
     */
    body: {
        /**
         * 老板应付金额（十进制字符串分，>0）
         */
        amountFen: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/tenant/finance-rules/split-preview';
};

export type TenantFinancePreviewResponses = {
    200: {
        /**
         * 分账试算结果
         */
        data: {
            /**
             * 平台服务费（十进制字符串分，>=0）
             */
            platformFeeFen: string;
            /**
             * 门店抽成（十进制字符串分，>=0）
             */
            storeCutFen: string;
            /**
             * 陪玩到手（十进制字符串分，>=0）
             */
            playerShareFen: string;
        };
    };
};

export type TenantFinancePreviewResponse = TenantFinancePreviewResponses[keyof TenantFinancePreviewResponses];

export type AccountingAccountingData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/tenant/orders/{orderId}/accounting';
};

export type AccountingAccountingResponses = {
    201: {
        /**
         * 订单核算结果
         */
        data: {
            /**
             * earning id
             */
            earningId: string;
            /**
             * 陪玩分成（十进制字符串分，>=0）
             */
            playerShareFen: string;
        };
    };
};

export type AccountingAccountingResponse = AccountingAccountingResponses[keyof AccountingAccountingResponses];

export type PlayerFinanceFinanceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/player/finance';
};

export type PlayerFinanceFinanceResponses = {
    200: {
        /**
         * 陪玩财务汇总
         */
        data: {
            /**
             * 待入账金额（十进制字符串分，>=0）
             */
            pendingFen: string;
            /**
             * 已入批金额（十进制字符串分，>=0）
             */
            batchedFen: string;
            /**
             * 已支付金额（十进制字符串分，>=0）
             */
            paidFen: string;
        };
    };
};

export type PlayerFinanceFinanceResponse = PlayerFinanceFinanceResponses[keyof PlayerFinanceFinanceResponses];

export type SettlementsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/settlements';
};

export type SettlementsListResponses = {
    200: unknown;
};

export type SettlementsCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/settlements';
};

export type SettlementsCreateResponses = {
    201: unknown;
};

export type SettlementsAddItemsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/settlements/{id}/items';
};

export type SettlementsAddItemsResponses = {
    201: unknown;
};

export type SettlementsReviewData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/settlements/{id}/review';
};

export type SettlementsReviewResponses = {
    201: unknown;
};

export type SettlementsApproveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/settlements/{id}/approve';
};

export type SettlementsApproveResponses = {
    201: unknown;
};

export type SettlementsPayData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/settlements/{id}/pay';
};

export type SettlementsPayResponses = {
    201: unknown;
};

export type SettlementsVoidBatchData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/settlements/{id}/void';
};

export type SettlementsVoidBatchResponses = {
    201: unknown;
};

export type PlayersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/players';
};

export type PlayersListResponses = {
    200: unknown;
};

export type PlayersCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/players';
};

export type PlayersCreateResponses = {
    201: unknown;
};

export type PlayersRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/players/{id}';
};

export type PlayersRemoveResponses = {
    200: unknown;
};

export type PlayersGetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/players/{id}';
};

export type PlayersGetResponses = {
    200: unknown;
};

export type PlayersUpdateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/players/{id}';
};

export type PlayersUpdateResponses = {
    200: unknown;
};

export type PlayersAddSkillData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/players/{id}/skills';
};

export type PlayersAddSkillResponses = {
    201: unknown;
};

export type PlayersRemoveSkillData = {
    body?: never;
    path: {
        id: string;
        skillId: string;
    };
    query?: never;
    url: '/api/v1/tenant/players/{id}/skills/{skillId}';
};

export type PlayersRemoveSkillResponses = {
    200: unknown;
};

export type PlayersAddAvailabilityData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/players/{id}/availability';
};

export type PlayersAddAvailabilityResponses = {
    201: unknown;
};

export type PlayersBindData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/players/{id}/account';
};

export type PlayersBindResponses = {
    201: unknown;
};

export type PlayersRemoveAvailabilityData = {
    body?: never;
    path: {
        id: string;
        availabilityId: string;
    };
    query?: never;
    url: '/api/v1/tenant/players/{id}/availability/{availabilityId}';
};

export type PlayersRemoveAvailabilityResponses = {
    200: unknown;
};

export type PlayerSelfMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/player/me';
};

export type PlayerSelfMeResponses = {
    200: unknown;
};

export type PlayerSelfUpdateMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/player/me';
};

export type PlayerSelfUpdateMeResponses = {
    200: unknown;
};

export type PlayerSelfAddAvailabilityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/player/availability';
};

export type PlayerSelfAddAvailabilityResponses = {
    201: unknown;
};

export type PlayerSelfRemoveAvailabilityData = {
    body?: never;
    path: {
        availabilityId: string;
    };
    query?: never;
    url: '/api/v1/tenant/player/availability/{availabilityId}';
};

export type PlayerSelfRemoveAvailabilityResponses = {
    200: unknown;
};

export type CatalogListGamesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/catalog/games';
};

export type CatalogListGamesResponses = {
    200: unknown;
};

export type CatalogCreateGameData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/catalog/games';
};

export type CatalogCreateGameResponses = {
    201: unknown;
};

export type CatalogRemoveGameData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/catalog/games/{id}';
};

export type CatalogRemoveGameResponses = {
    200: unknown;
};

export type CatalogUpdateGameData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/catalog/games/{id}';
};

export type CatalogUpdateGameResponses = {
    200: unknown;
};

export type CatalogListRegionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/catalog/regions';
};

export type CatalogListRegionsResponses = {
    200: unknown;
};

export type CatalogCreateRegionData = {
    body?: never;
    path: {
        gameId: string;
    };
    query?: never;
    url: '/api/v1/tenant/catalog/games/{gameId}/regions';
};

export type CatalogCreateRegionResponses = {
    201: unknown;
};

export type CatalogRemoveRegionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/catalog/regions/{id}';
};

export type CatalogRemoveRegionResponses = {
    200: unknown;
};

export type CatalogUpdateRegionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/catalog/regions/{id}';
};

export type CatalogUpdateRegionResponses = {
    200: unknown;
};

export type CatalogListProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/catalog/products';
};

export type CatalogListProductsResponses = {
    200: unknown;
};

export type CatalogCreateProductData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/catalog/products';
};

export type CatalogCreateProductResponses = {
    201: unknown;
};

export type CatalogRemoveProductData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/catalog/products/{id}';
};

export type CatalogRemoveProductResponses = {
    200: unknown;
};

export type CatalogUpdateProductData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/catalog/products/{id}';
};

export type CatalogUpdateProductResponses = {
    200: unknown;
};

export type CatalogListRulesData = {
    body?: never;
    path: {
        productId: string;
    };
    query?: never;
    url: '/api/v1/tenant/catalog/products/{productId}/pricing';
};

export type CatalogListRulesResponses = {
    200: {
        data: Array<{
            /**
             * 价格规则 id
             */
            id: string;
            /**
             * 租户 id
             */
            tenantId: string;
            /**
             * 服务产品 id
             */
            serviceProductId: string;
            /**
             * 时长（秒）
             */
            durationSeconds: number;
            /**
             * 售价（十进制字符串分，>0）
             */
            priceFen: string;
            /**
             * 陪玩成本（十进制字符串分，>=0）
             */
            playerCostFen: string;
            /**
             * 是否启用
             */
            enabled: boolean;
            /**
             * 创建时间
             */
            createdAt: string;
            /**
             * 更新时间
             */
            updatedAt: string;
        }>;
    };
};

export type CatalogListRulesResponse = CatalogListRulesResponses[keyof CatalogListRulesResponses];

export type CatalogCreateRuleData = {
    /**
     * 创建价格规则
     */
    body: {
        /**
         * 时长（秒）
         */
        durationSeconds: number;
        /**
         * 售价（十进制字符串分，>0）
         */
        priceFen: string;
        /**
         * 陪玩成本（十进制字符串分，>=0）
         */
        playerCostFen?: string;
        /**
         * 是否启用
         */
        enabled?: boolean;
    };
    path: {
        productId: string;
    };
    query?: never;
    url: '/api/v1/tenant/catalog/products/{productId}/pricing';
};

export type CatalogCreateRuleResponses = {
    201: {
        /**
         * 价格规则（金额字段为十进制字符串分）
         */
        data: {
            /**
             * 价格规则 id
             */
            id: string;
            /**
             * 租户 id
             */
            tenantId: string;
            /**
             * 服务产品 id
             */
            serviceProductId: string;
            /**
             * 时长（秒）
             */
            durationSeconds: number;
            /**
             * 售价（十进制字符串分，>0）
             */
            priceFen: string;
            /**
             * 陪玩成本（十进制字符串分，>=0）
             */
            playerCostFen: string;
            /**
             * 是否启用
             */
            enabled: boolean;
            /**
             * 创建时间
             */
            createdAt: string;
            /**
             * 更新时间
             */
            updatedAt: string;
        };
    };
};

export type CatalogCreateRuleResponse = CatalogCreateRuleResponses[keyof CatalogCreateRuleResponses];

export type CatalogRemoveRuleData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/catalog/pricing/{id}';
};

export type CatalogRemoveRuleResponses = {
    200: unknown;
};

export type CatalogUpdateRuleData = {
    /**
     * 更新价格规则
     */
    body: {
        /**
         * 时长（秒）
         */
        durationSeconds?: number;
        /**
         * 售价（十进制字符串分，>0）
         */
        priceFen?: string;
        /**
         * 陪玩成本（十进制字符串分，>=0）
         */
        playerCostFen?: string;
        /**
         * 是否启用
         */
        enabled?: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/catalog/pricing/{id}';
};

export type CatalogUpdateRuleResponses = {
    200: {
        /**
         * 价格规则（金额字段为十进制字符串分）
         */
        data: {
            /**
             * 价格规则 id
             */
            id: string;
            /**
             * 租户 id
             */
            tenantId: string;
            /**
             * 服务产品 id
             */
            serviceProductId: string;
            /**
             * 时长（秒）
             */
            durationSeconds: number;
            /**
             * 售价（十进制字符串分，>0）
             */
            priceFen: string;
            /**
             * 陪玩成本（十进制字符串分，>=0）
             */
            playerCostFen: string;
            /**
             * 是否启用
             */
            enabled: boolean;
            /**
             * 创建时间
             */
            createdAt: string;
            /**
             * 更新时间
             */
            updatedAt: string;
        };
    };
};

export type CatalogUpdateRuleResponse = CatalogUpdateRuleResponses[keyof CatalogUpdateRuleResponses];

export type DispatchAdminPublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/orders/{id}/publish';
};

export type DispatchAdminPublishResponses = {
    201: unknown;
};

export type DispatchAdminApplicationsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/orders/{id}/applications';
};

export type DispatchAdminApplicationsResponses = {
    200: unknown;
};

export type DispatchAdminShortlistData = {
    body?: never;
    path: {
        id: string;
        applicationId: string;
    };
    query?: never;
    url: '/api/v1/tenant/orders/{id}/applications/{applicationId}/shortlist';
};

export type DispatchAdminShortlistResponses = {
    201: unknown;
};

export type DispatchAdminAssignData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/orders/{id}/assignment';
};

export type DispatchAdminAssignResponses = {
    201: unknown;
};

export type DispatchPlayerHallData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/player/order-hall';
};

export type DispatchPlayerHallResponses = {
    200: {
        data: Array<{
            /**
             * 订单 id
             */
            id: string;
            /**
             * 订单号
             */
            orderNo: string;
            /**
             * 产品名
             */
            productName: string;
            /**
             * 时长（秒）
             */
            durationSeconds: number;
            /**
             * 单价（十进制字符串分，>0）
             */
            unitPriceFen: string;
            /**
             * 期望开始
             */
            desiredStartAt: string | null;
            /**
             * 创建时间
             */
            createdAt: string;
        }>;
    };
};

export type DispatchPlayerHallResponse = DispatchPlayerHallResponses[keyof DispatchPlayerHallResponses];

export type DispatchPlayerMineData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/player/applications';
};

export type DispatchPlayerMineResponses = {
    200: unknown;
};

export type DispatchPlayerApplyData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/tenant/player/orders/{orderId}/applications';
};

export type DispatchPlayerApplyResponses = {
    201: unknown;
};

export type DispatchCustomerCandidatesData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/tenant/customer/orders/{orderId}/applications';
};

export type DispatchCustomerCandidatesResponses = {
    200: unknown;
};

export type DispatchCustomerSelectData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/tenant/customer/orders/{orderId}/assignment';
};

export type DispatchCustomerSelectResponses = {
    201: unknown;
};

export type SessionsSessionData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/tenant/orders/{orderId}/session';
};

export type SessionsSessionResponses = {
    200: unknown;
};

export type SessionsStartData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/tenant/orders/{orderId}/session/start';
};

export type SessionsStartResponses = {
    201: unknown;
};

export type SessionsEndData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/tenant/orders/{orderId}/session/end';
};

export type SessionsEndResponses = {
    201: unknown;
};

export type SessionsAdjustData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/api/v1/tenant/sessions/{sessionId}/adjustments';
};

export type SessionsAdjustResponses = {
    201: unknown;
};

export type SessionsReviewData = {
    body?: never;
    path: {
        sessionId: string;
        adjustmentId: string;
    };
    query?: never;
    url: '/api/v1/tenant/sessions/{sessionId}/adjustments/{adjustmentId}/review';
};

export type SessionsReviewResponses = {
    201: unknown;
};

export type EvidenceUploadData = {
    body?: never;
    headers: {
        'x-file-name': string;
    };
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/api/v1/tenant/sessions/{sessionId}/evidence';
};

export type EvidenceUploadResponses = {
    201: unknown;
};

export type EvidenceDownloadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/evidence/{id}';
};

export type EvidenceDownloadResponses = {
    200: unknown;
};

export type DisputesListAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/disputes';
};

export type DisputesListAllResponses = {
    200: unknown;
};

export type DisputesListData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/tenant/orders/{orderId}/disputes';
};

export type DisputesListResponses = {
    200: unknown;
};

export type DisputesOpenData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/tenant/orders/{orderId}/disputes';
};

export type DisputesOpenResponses = {
    201: unknown;
};

export type DisputesResolveData = {
    body?: never;
    path: {
        disputeId: string;
    };
    query?: never;
    url: '/api/v1/tenant/disputes/{disputeId}/resolve';
};

export type DisputesResolveResponses = {
    201: unknown;
};

export type NotificationsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/notifications';
};

export type NotificationsListResponses = {
    200: unknown;
};

export type NotificationsMarkReadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/tenant/notifications/{id}/read';
};

export type NotificationsMarkReadResponses = {
    201: unknown;
};

export type NotificationsMarkAllReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/notifications/read-all';
};

export type NotificationsMarkAllReadResponses = {
    201: unknown;
};

export type AiCapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/ai/capabilities';
};

export type AiCapabilitiesResponses = {
    200: unknown;
};

export type AiParseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenant/ai/parse-requirement';
};

export type AiParseResponses = {
    201: unknown;
};

export type AiRecommendData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/v1/tenant/ai/orders/{orderId}/recommendations';
};

export type AiRecommendResponses = {
    200: unknown;
};

export type PlatformBillingPackagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/platform/packages';
};

export type PlatformBillingPackagesResponses = {
    200: unknown;
};

export type PlatformBillingOnboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/platform/onboarding/tenants';
};

export type PlatformBillingOnboardResponses = {
    201: unknown;
};

export type PlatformBillingAssignData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/api/v1/platform/tenants/{tenantId}/package';
};

export type PlatformBillingAssignResponses = {
    201: unknown;
};

export type PlatformBillingActivateData = {
    body?: never;
    path: {
        tenantId: string;
    };
    query?: never;
    url: '/api/v1/platform/tenants/{tenantId}/activate';
};

export type PlatformBillingActivateResponses = {
    201: unknown;
};
